### Начало работы всей системы, стартует загрузку устройства с заданными настройками и версией

POST http://0.0.0.0:6064/start HTTP/1.1
content-type: application/json
auth: very-secure-token

### Отправка (эмуляция аппаратного включения) ключа технического специалиста (для работы с системой нужны ключи и технического специалиста и специалиста по безопасности)

POST http://0.0.0.0:6064/key_in HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "name": "Technical"
} 

### Отправка ключа специалиста по безопасности

POST http://0.0.0.0:6064/key_in HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "name": "Security"
} 

### Извлечение ключа технического специалиста (служебный порт прекращает работу только по извлечению обоих ключей)

POST http://0.0.0.0:6064/key_out HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "name": "Technical"
} 

### Извлечение ключа специалиста по безопасности (служебный порт прекращает работу только по извлечению обоих ключей)

POST http://0.0.0.0:6064/key_out HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "name": "Security"
} 

### Остановка всех процессов в системе, требует start после себя, чтобы начать выполнение повторно с обнулением изменений в значениях переменных (но не в файлах настроек и версий).

POST http://0.0.0.0:6064/stop HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    
} 